# Generated by Django 3.2.8 on 2021-10-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0004_alter_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
