# Generated by Django 3.2.8 on 2021-10-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0006_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='pattern',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
