# Generated by Django 3.2.8 on 2021-10-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0007_userdata_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='userdata',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
