# Generated by Django 3.2.8 on 2021-10-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0008_auto_20211023_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='pattern',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
