# Generated by Django 3.2.8 on 2021-10-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0009_auto_20211023_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='pattern',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
