# Generated by Django 3.2.8 on 2021-10-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0010_alter_userdata_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='secret_key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
