# Generated by Django 3.2.8 on 2021-10-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0011_userdata_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='text_encrypt',
            field=models.BinaryField(null=True),
        ),
    ]
