# Generated by Django 3.2.8 on 2021-10-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0012_userdata_text_encrypt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='text_encrypt',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
